### ISSUE TITLE
In immortalwrt-23.05.0-rc3 ,openvpn-socks5 not working!

### ISSUE THREAD

**Issue by science2468** [nanpuyue/openvpn-socks5#2]
![image](https://github.com/nanpuyue/openvpn-socks5/assets/102643084/2563d78b-441f-4a91-b5e8-29aa9ebef09f)
![image](https://github.com/nanpuyue/openvpn-socks5/assets/102643084/c3cc10d0-003b-4040-85c0-4c9fba89ee9c)
![image](https://github.com/nanpuyue/openvpn-socks5/assets/102643084/d1d66d3f-4e65-41f0-9e1e-d65380cfabdc)

**Comment by nanpuyue** [comment]
首先你得保证容器内能够访问外部网络连接到服务器。

**Comment by science2468** [comment]
> 首先你得保证容器内能够访问外部网络连接到服务器。

之后尝试了把docker0的流量转发到wan区域才有网。
